### ISSUE TITLE
Layperson's use of SimpleDemo

### ISSUE THREAD

**Issue by dr-parker** [jmacglashan/gltl#1]
Hello, I am trying to run this SimpleDemo, but not entirely sure what I should be expecting. I'm a novice user and was trying to gain more insights into the example provided in a recent paper: "Environment-Independent Task Specification via GLTL" I'm guessing that SimpleDemo may not be the same example provided in the paper, but I'm also just trying to get some guidance on if the output I receiving looks familiar to the authors (as well as the Exceptions that follow). Any insight would be much appreciated. Thanks!

Running for formula 4
{2=[4]}
2, 1
1.0->1
2, 0
1.0->0
=========
Starting reachability analysis
Exception in thread "main" java.lang.RuntimeException: Symbol 4 cannot be evaluated because it is undefined
	at gltl.compiler.GLTLCompiler$SymbolEvaluator.eval(GLTLCompiler.java:449)
	at gltl.compiler.GLTLCompiler$CompiledAction.getTaskTransitions(GLTLCompiler.java:256)
	at gltl.compiler.GLTLCompiler$CompiledAction.getTransitions(GLTLCompiler.java:204)
	at burlap.behavior.singleagent.planning.ActionTransitions.<init>(ActionTransitions.java:46)
	at burlap.behavior.singleagent.planning.ValueFunctionPlanner.getActionsTransitions(ValueFunctionPlanner.java:331)
	at burlap.behavior.singleagent.planning.stochastic.valueiteration.ValueIteration.performReachabilityFrom(ValueIteration.java:203)
	at burlap.behavior.singleagent.planning.stochastic.valueiteration.ValueIteration.planFromState(ValueIteration.java:109)
	at gltl.demo.SimpleDemo.main(SimpleDemo.java:66)

**Comment by mlittman** [comment]
Hi Lonnie,

I suspect I am the only one listening. :-)

I'm not very good at github, so I'm not sure I can be super helpful via
email. But, I think what you are saying is that you ran "simpledemo" and
got an error. I don't think simpledemo is what i was using, though. Are
there other options? The main file I was working with had a bunch of
commented out prefix expressions near the top.

-Michael
